### ISSUE TITLE
UI: Create Home Page

### ISSUE THREAD

**Issue by Mustafa2856** [AOSP-NIT-Surat/Bookstore-Android#4]
Add options for:

- [x] Selling a book (Floating Action Button)

- [x] Searching for books in store

**Comment by unnikrishnan2002** [comment]
I would like to work on it can you please assign it to me? @Mustafa2856

**Comment by Mustafa2856** [comment]
Sure, i will assign you the issue

**Comment by unnikrishnan2002** [comment]
Hey @Mustafa2856 the search button for bookstore is to be placed on the Fab button or at the top the page like a searchbar?

**Comment by Mustafa2856** [comment]
It should  be a search bar

**Comment by unnikrishnan2002** [comment]
@Mustafa2856 
PR submitted - #6
