### ISSUE TITLE
feat: add ui to view user profile (user profile page)

### ISSUE THREAD

**Issue by Mustafa2856** [AOSP-NIT-Surat/Bookstore-Android#8]
It should include:

- [ ] their profile pic (if any)
- [ ] Name
- [ ] Email
- [ ] List of books they are selling
- [ ] Contact -no.
- [ ] Location

**Comment by unnikrishnan2002** [comment]
Can I continue working on this issue as well ? @Mustafa2856

**Comment by Mustafa2856** [comment]
@unnikrishnan2002 Sure

**Comment by unnikrishnan2002** [comment]
Hey @Mustafa2856 I have created this [Wireframe for this UI](https://whimsical.com/profile-page-ui-design-CHoBY99hHyUYhHb8VSNZZk) please check it and suggest changes if needed

**Comment by Mustafa2856** [comment]
@unnikrishnan2002  Looks good go ahead

**Comment by unnikrishnan2002** [comment]
@Mustafa2856 should I give an intent from the sell books FAB button to this page?

**Comment by Mustafa2856** [comment]
@unnikrishnan2002  yes

**Comment by unnikrishnan2002** [comment]
> @unnikrishnan2002 yes

Done , PR submitted  @Mustafa2856
